### PR TITLE
Update Moroccan Arabic language

### LINKED ISSUE #74: Update Moroccan Arabic language
See downstream task at [T237672](https://phabricator.wikimedia.org/T237672).

### PR DESCRIPTION
**Pull request by SADIQUI**
As requested in <a href="https://phabricator.wikimedia.org/T237672">T237672</a>.

Fixes #74

### CODE REVIEW

**Comment by MarcoAurelioWM** [comment]
Hi @SADIQUI. Where the contents of `language-data.json` generated by `php ulsdata2json.php` or manually?

**Comment by SADIQUI** [comment]
@MarcoAurelioWM, the contents of  `language-data.json` were generated manually.

**Comment by MarcoAurelioWM** [comment]
> @MarcoAurelioWM, the contents of `language-data.json` were generated manually.

Please don't do that. See https://github.com/wikimedia/language-data/blob/master/README.md You just need to update langdb.yaml and after that run PHP script as stated in the README file.

**Comment by SADIQUI** [comment]
> Contents of language-data.json must not be generated manually but by running a PHP script as stated in https://github.com/wikimedia/language-data/blob/master/README.md. You just need to do changes in langdb.yaml.

I returned `language-data.json` to the original version. This is what I understood, Is it good now?

**Comment by MarcoAurelioWM** [comment]
> > Contents of language-data.json must not be generated manually but by running a PHP script as stated in https://github.com/wikimedia/language-data/blob/master/README.md. You just need to do changes in langdb.yaml.
> 
> I returned `language-data.json` to the original version. This is what I understood, Is it good now?

You now have to run `php data/ulsdata2json.php` and commit the changes that the script makes in `language-data.json`.

**Comment by SADIQUI** [comment]
> > > Contents of language-data.json must not be generated manually but by running a PHP script as stated in https://github.com/wikimedia/language-data/blob/master/README.md. You just need to do changes in langdb.yaml.
> > 
> > 
> > I returned `language-data.json` to the original version. This is what I understood, Is it good now?
> 
> You now have to run `php data/ulsdata2json.php` and commit the changes that the script makes in `language-data.json`.

@MarcoAurelioWM  I did just what you said, I run `data/ulsdata2json.php`. I deleted the old `language-data.json`. & I uploaded the new `language-data.json` that generated by script. I think it's good now.

**Comment by amire80** [comment]
Thanks. This is out of date, and I'll do it in another pull request.

**Pull request closed without merging**
