### PR TITLE
Add Assyrian Neo-Aramaic (aii)

### PR DESCRIPTION
**Pull request by ledzeppelin**

### CODE REVIEW

**Comment by ledzeppelin** [comment]
creating this pr to add aii to https://translatewiki.net/ so that the aii language wikipedia can be complete the incubation process

**Review by srish — CHANGES_REQUESTED** [review]
Hi! Thanks for the patch. Could you share more about the source for the name `ܣܘܪܝܐ`? This name appears neither in [Ethnologue](https://iso639-3.sil.org/code/aii) or [Wikipedia](https://en.wikipedia.org/wiki/Suret_language). 

To enable the language on Translatewiki, you will also need to request this on the [Support page for Translatewiki.net](https://translatewiki.net/wiki/Support).

**Comment by ledzeppelin** [comment]
> Hi! Thanks for the patch. Could you share more about the source for the name `ܣܘܪܝܐ`? This name appears neither in [Ethnologue](https://iso639-3.sil.org/code/aii) or [Wikipedia](https://en.wikipedia.org/wiki/Suret_language).
> 
> To enable the language on Translatewiki, you will also need to request this on the [Support page for Translatewiki.net](https://translatewiki.net/wiki/Support).

thanks so much for the feedback, i renamed the autonym to what is being referenced in the wikipedia article

**Review by amire80 — APPROVED** [review]
Thanks!

For "paper trail", downstream task: https://phabricator.wikimedia.org/T369727

**Review by srish — APPROVED** [review]

**Pull request merged**
