### PR TITLE
Change simple => en-simple

### PR DESCRIPTION
**Pull request by arlolra**
To match mediawiki core,
https://github.com/wikimedia/mediawiki/commit/21ead7a98d1a103b77f1e3ba29a85493782d398b

This was noticed when trying to choose Simple Wikipedia from the ULS and
finding that on pages with many languages (like, Red) it wasn't
available in the search.

```
<li class="interlanguage-link interwiki-simple"><a href="https://simple.wikipedia.org/wiki/Red" title="Red – Simple English" lang="en-simple" hreflang="en-simple" class="interlanguage-link-target">Simple English</a></li>
```

Assuming this need to be pulled in jquery.uls and then that needs to be
pulled in mediawiki-extensions-UniversalLanguageSelector

cc/ @cscott

### CODE REVIEW

**Comment by Nikerabbit** [comment]
This might break stuff unexpectedly. Should at least leave a redirect from simple in place for now, and check how this works with CX and ULS.

**Comment by cscott** [comment]
So, let's see: the actual HTML `lang` attributes are going to be valid BCP-47 now (as of last week's train).  If you're reading the attributes on the page using JS DOM access, then you should probably update your data to match `$nonstandardLanguageCodeMapping` in https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/460038/7/languages/LanguageCode.php

This is available from `mediawiki.language.bcp47()` in client-side JS as well, but that probably doesn't help you much.

I think there's only one instance (`als` which should be `gsw`) where the nonstandard MediaWiki-internal codes are actually valid BCP-47 codes (but for the "wrong" language).  So it should be safe just to add both the "old" and the "new" names to your tables, perhaps with an annotation that the old name is nonstandard and present only for backward compatibility.

But I'm wondering why we've got multiple copies of the autonym data; this is also present in `languages/data/Names.php` in core.  Could we make this a dual JS/PHP library and replace the copy in core with this data imported as a composer library?

**Comment by cscott** [comment]
Created #37 as a somewhat more-ambitious version of this PR.

**Comment by Nikerabbit** [comment]
ULS extensions adds override for als: https://gerrit.wikimedia.org/g/mediawiki/extensions/UniversalLanguageSelector/+/fd00f8ab1861ccede91d62127c6e9c62d1549b68/resources/js/ext.uls.common.js#31

Multiple copies of autonym data: that is https://phabricator.wikimedia.org/T190129 and I am proposing it to be picked up in Language team's maintenance work this fiscal year.

**Comment by arlolra** [comment]
Closing in favour of what looks like a more complete patch in #37 and the issue being tracked in https://phabricator.wikimedia.org/T207791

**Pull request closed without merging**
